#:schema node_modules/wrangler/config-schema.json
name = "server"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [{name = "DOC", class_name = "Doc"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Doc"]